ckpt_repo: amphion/naturalspeech3_facodec
encoder:
  ngf: 32
  up_ratios: [2, 4, 5, 5]
  out_channels: 256
  ckpt_filename: ns3_facodec_encoder.bin
decoder:
  in_channels: 256
  upsample_initial_channel: 1024
  ngf: 32
  up_ratios: [5, 5, 4, 2]
  vq_num_q_c: 2
  vq_num_q_p: 1
  vq_num_q_r: 3
  vq_dim: 256
  codebook_dim: 8
  codebook_size_prosody: 10
  codebook_size_content: 10
  codebook_size_residual: 10
  use_gr_x_timbre: true
  use_gr_residual_f0: true
  use_gr_residual_phone: true
  ckpt_filename: ns3_facodec_decoder.bin