num_query_tokens: 4
hidden_size: 256
num_hidden_layers: 4
num_attention_heads: 4
cross_attention_frequency: 1
encoder_hidden_size: 256
bert_pretrained: google/bert_uncased_L-4_H-256_A-4
ckpt: mini_bert